spring:
  application: demo
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-5
          temperature: 1.0
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      chat:
        options:
          model: claude-sonnet-4-5-20250929
    mcp:
      client:
        enabled: on
        sse:
          connections:
            mcp-confluent:
              url: https://mcp-confluent.ai-assisted.engineering
              sse-endpoint: /sse
        toolcallback:
          enabled: on
        type: sync
        request-timeout: 60s
  main:
    web-application-type: none

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %clr(%-5level){green} %clr(%logger{20}){cyan} - %msg%n"
  level:
    root: WARN
    com.example.demo: DEBUG
    org.springframework.ai: INFO
    io.modelcontextprotocol: INFO
    